// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SharedTenant.Models
{
    public partial class BookStores
    {
        public int Id { get; set; }
        public string Domain { get; set; }
        public string ConnectionString { get; set; }
    }
}