// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SharedTenant.Models
{
    public partial class BookStores
    {
        public int Id { get; set; }
        [Required]
        public string Domain { get; set; }
        [Required]
        public string ConnectionString { get; set; }
        [Required]
        public string UrlName { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public string Logo { get; set; }
        [Required]
        public string Address { get; set; }
        [Required]
        public DateTime EndSubscriptionDate { get; set; }
    }
}