// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SharedTenant.Models
{
    public partial class CustomerLoveCategory
    {
        public int CustomerLoveCategoryId { get; set; }
        public string CutomerId { get; set; }
        public int? CategoryId { get; set; }
        public int? LoveRate { get; set; }

        public virtual ExchangBookCategory Category { get; set; }
    }
}