// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SharedTenant.Models
{
    public partial class CustomerCategoryBookRate
    {
        public string CustomerId { get; set; }
        public int? CategoryId { get; set; }
        public int? BookId { get; set; }
        public int? LoveRate { get; set; }
        public int TableId { get; set; }
        public bool? Processed { get; set; }

        public virtual BooksForExchange Book { get; set; }
        public virtual ExchangBookCategory Category { get; set; }
    }
}