// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SharedTenant.Models
{
    public partial class ExchangBookCategory
    {
        public ExchangBookCategory()
        {
            CustomerCategoryBookRate = new HashSet<CustomerCategoryBookRate>();
            CustomerLoveCategory = new HashSet<CustomerLoveCategory>();
            ExchangeBookCategoryList = new HashSet<ExchangeBookCategoryList>();
        }

        public int CategoryId { get; set; }
        public string CategoryName { get; set; }
        public string CategoryPhoto { get; set; }

        public virtual ICollection<CustomerCategoryBookRate> CustomerCategoryBookRate { get; set; }
        public virtual ICollection<CustomerLoveCategory> CustomerLoveCategory { get; set; }
        public virtual ICollection<ExchangeBookCategoryList> ExchangeBookCategoryList { get; set; }
    }
}