// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using SharedTenant.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace SharedTenant.Models
{
    public partial interface ISharedtenantContextProcedures
    {
        Task<int> UpdateInterestAsync(string UserId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
