// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using SharedTenant.Domain;

#nullable disable

namespace SharedTenant.Models
{
    public partial class SharedtenantContext : IdentityDbContext<ApplicationUser>
    {
        public SharedtenantContext()
        {
        }

        public SharedtenantContext(DbContextOptions<SharedtenantContext> options)
            : base(options)
        {
        }

        public virtual DbSet<BookStores> BookStores { get; set; }
        public virtual DbSet<BooksForExchange> BooksForExchange { get; set; }
        public virtual DbSet<CustomerCategoryBookRate> CustomerCategoryBookRate { get; set; }
        public virtual DbSet<CustomerLoveCategory> CustomerLoveCategory { get; set; }
        public virtual DbSet<CustomerRecomendedBook> CustomerRecomendedBook { get; set; }
        public virtual DbSet<ExchangBookCategory> ExchangBookCategory { get; set; }
        public virtual DbSet<ExchangeBookCategoryList> ExchangeBookCategoryList { get; set; }
        public virtual DbSet<Wishlist> Wishlist { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS");

            modelBuilder.Entity<BookStores>(entity =>
            {
                entity.Property(e => e.Address)
                    .IsRequired()
                    .HasMaxLength(120);

                entity.Property(e => e.ConnectionString)
                    .IsRequired()
                    .HasMaxLength(200);

                entity.Property(e => e.Domain)
                    .IsRequired()
                    .HasMaxLength(100);

                entity.Property(e => e.EndSubscriptionDate).HasColumnType("datetime");

                entity.Property(e => e.Logo).HasMaxLength(50);

                entity.Property(e => e.Name).HasMaxLength(50);

                entity.Property(e => e.UrlName).HasMaxLength(150);
            });

            modelBuilder.Entity<BooksForExchange>(entity =>
            {
                entity.HasKey(e => e.ExchageBookId);

                entity.Property(e => e.AduioUrl).HasMaxLength(50);

                entity.Property(e => e.AuthorName).HasMaxLength(70);

                entity.Property(e => e.Description).HasMaxLength(1000);

                entity.Property(e => e.Name).HasMaxLength(70);

                entity.Property(e => e.OwnerId).HasMaxLength(450);

                entity.Property(e => e.PdfUrl).HasMaxLength(50);

                entity.Property(e => e.Photo).HasMaxLength(70);

                entity.Property(e => e.UrlName).HasMaxLength(70);
            });

            modelBuilder.Entity<CustomerCategoryBookRate>(entity =>
            {
                entity.HasKey(e => e.TableId);

                entity.ToTable("Customer_Category_Book_Rate");

                entity.Property(e => e.TableId).HasColumnName("TableID");

                entity.Property(e => e.BookId).HasColumnName("BookID");

                entity.Property(e => e.CategoryId).HasColumnName("CategoryID");

                entity.Property(e => e.CustomerId)
                    .HasMaxLength(450)
                    .HasColumnName("CustomerID");

                entity.Property(e => e.Processed)
                    .HasColumnName("processed")
                    .HasDefaultValueSql("((0))");

                entity.HasOne(d => d.Book)
                    .WithMany(p => p.CustomerCategoryBookRate)
                    .HasForeignKey(d => d.BookId)
                    .HasConstraintName("FK_Customer_Category_Book_Rate_BooksForExchange");

                entity.HasOne(d => d.Category)
                    .WithMany(p => p.CustomerCategoryBookRate)
                    .HasForeignKey(d => d.CategoryId)
                    .HasConstraintName("FK_Customer_Category_Book_Rate_ExchangBookCategory");
            });

            modelBuilder.Entity<CustomerLoveCategory>(entity =>
            {
                entity.Property(e => e.CutomerId).HasMaxLength(450);

                entity.HasOne(d => d.Category)
                    .WithMany(p => p.CustomerLoveCategory)
                    .HasForeignKey(d => d.CategoryId)
                    .OnDelete(DeleteBehavior.Cascade)
                    .HasConstraintName("FK_CustomerLoveCategory_ExchangBookCategory");
            });

            modelBuilder.Entity<CustomerRecomendedBook>(entity =>
            {
                entity.Property(e => e.CustomerId).HasMaxLength(450);

                entity.HasOne(d => d.Book)
                    .WithMany(p => p.CustomerRecomendedBook)
                    .HasForeignKey(d => d.BookId)
                    .OnDelete(DeleteBehavior.Cascade)
                    .HasConstraintName("FK_CustomerRecomendedBook_BooksForExchange");
            });

            modelBuilder.Entity<ExchangBookCategory>(entity =>
            {
                entity.HasKey(e => e.CategoryId);

                entity.Property(e => e.CategoryName).HasMaxLength(100);

                entity.Property(e => e.CategoryPhoto).HasMaxLength(265);
            });

            modelBuilder.Entity<ExchangeBookCategoryList>(entity =>
            {
                entity.HasOne(d => d.Book)
                    .WithMany(p => p.ExchangeBookCategoryList)
                    .HasForeignKey(d => d.BookId)
                    .OnDelete(DeleteBehavior.Cascade)
                    .HasConstraintName("FK_ExchangeBookCategoryList_BooksForExchange");

                entity.HasOne(d => d.Categroy)
                    .WithMany(p => p.ExchangeBookCategoryList)
                    .HasForeignKey(d => d.CategroyId)
                    .OnDelete(DeleteBehavior.Cascade)
                    .HasConstraintName("FK_ExchangeBookCategoryList_ExchangBookCategory");
            });

            modelBuilder.Entity<Wishlist>(entity =>
            {
                entity.HasKey(e => e.WishId);

                entity.Property(e => e.WishId).HasColumnName("WishID");

                entity.Property(e => e.BookId).HasColumnName("BookID");

                entity.Property(e => e.BookName)
                    .IsRequired()
                    .HasMaxLength(100);

                entity.Property(e => e.BookPhoto)
                    .IsRequired()
                    .HasMaxLength(100);

                entity.Property(e => e.BookStore)
                    .IsRequired()
                    .HasMaxLength(150);

                entity.Property(e => e.CustomerId)
                    .IsRequired()
                    .HasMaxLength(450)
                    .HasColumnName("CustomerID");
            });

            OnModelCreatingGeneratedProcedures(modelBuilder);
            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}