// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SharedTenant.Models
{
    public partial class Wishlist
    {
        public int WishId { get; set; }
        public string CustomerId { get; set; }
        public int BookId { get; set; }
        public string BookStore { get; set; }
        public string BookPhoto { get; set; }
        public string BookName { get; set; }
        public bool ForExchange { get; set; }
    }
}