// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace App.Core.Models
{
    public partial class Authors
    {
        public Authors()
        {
            Book = new HashSet<Book>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Photo { get; set; }
        public int DisplayOrder { get; set; }
        public short? NumberOfBooks { get; set; }

        public virtual ICollection<Book> Book { get; set; }
    }
}