// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace App.Core.Models
{
    public partial class KitabiContext : DbContext
    {
        public KitabiContext()
        {
        }

        public KitabiContext(DbContextOptions<KitabiContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Authors> Authors { get; set; }
        public virtual DbSet<Book> Book { get; set; }
        public virtual DbSet<BookCategory> BookCategory { get; set; }
        public virtual DbSet<BookCategoryList> BookCategoryList { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS");

            modelBuilder.Entity<Authors>(entity =>
            {
                entity.Property(e => e.Bio)
                    .IsRequired()
                    .HasMaxLength(300);

                entity.Property(e => e.DisplayOrder).HasDefaultValueSql("((99))");

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.Photo)
                    .IsRequired()
                    .HasMaxLength(50);
            });

            modelBuilder.Entity<Book>(entity =>
            {
                entity.HasIndex(e => e.UrlName, "IX_Book")
                    .IsUnique();

                entity.Property(e => e.AduioUrl).HasMaxLength(50);

                entity.Property(e => e.Description)
                    .IsRequired()
                    .HasMaxLength(1000);

                entity.Property(e => e.IsActive)
                    .IsRequired()
                    .HasDefaultValueSql("((1))");

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(70);

                entity.Property(e => e.PdfUrl).HasMaxLength(50);

                entity.Property(e => e.Photo)
                    .IsRequired()
                    .HasMaxLength(70);

                entity.Property(e => e.Price).HasColumnType("smallmoney");

                entity.Property(e => e.UrlName)
                    .IsRequired()
                    .HasMaxLength(70);

                entity.HasOne(d => d.Author)
                    .WithMany(p => p.Book)
                    .HasForeignKey(d => d.AuthorId)
                    .HasConstraintName("FK_Book_Authors");
            });

            modelBuilder.Entity<BookCategory>(entity =>
            {
                entity.Property(e => e.CategoryName)
                    .IsRequired()
                    .HasMaxLength(50);
            });

            modelBuilder.Entity<BookCategoryList>(entity =>
            {
                entity.HasKey(e => new { e.BookId, e.CategoryId });

                entity.HasOne(d => d.Book)
                    .WithMany(p => p.BookCategoryList)
                    .HasForeignKey(d => d.BookId)
                    .HasConstraintName("FK_BookCategoryList_Book");

                entity.HasOne(d => d.Category)
                    .WithMany(p => p.BookCategoryList)
                    .HasForeignKey(d => d.CategoryId)
                    .HasConstraintName("FK_BookCategoryList_BookCategory");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}